# Generated by Django 4.0.3 on 2022-06-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post_comment'),
        ),
    ]
