# Generated by Django 4.0.3 on 2022-06-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_comment_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.DeleteModel(
            name='Post_comment',
        ),
    ]
