# Generated by Django 3.2.12 on 2023-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.AddField(
            model_name='employee',
            name='profile',
            field=models.ImageField(default='profile.png', upload_to=''),
        ),
    ]
